### ISSUE TITLE
Hoyoplay Launcher requires update after fresh install

### ISSUE THREAD

**Issue by ChildishhAlbino** [moraroy/NonSteamLaunchersDecky#49]
Did a clean install to follow along with #48. After doing this I can't do anything as it requires an update that breaks the shortcut when applied.

![Image](https://github.com/user-attachments/assets/f210dce8-1f5e-4f67-aa77-9421f14feb7f)

Update wasn't required before but now seems to be.

**Comment by moraroy** [comment]
@ChildishhAlbino yeah update it all the way.. that's the launcher..... now in your library there will be a genshin shortcut that doesn't use the launcher.

**Comment by moraroy** [comment]
@ChildishhAlbino oh I see what you mean, didn't realize that was mandatory either. My fault i missunderstood you when you said a fresh install. You can try this in desktop mode

 navigate here
/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/users/steamuser/AppData/Roaming/Cognosphere/HYP/1_0/ 


and delete every folder except "data", "fedata" and "fepak". Then run your hoyo launcher. I guess now the goal would be to open the launcher to download genshin :/

**Comment by moraroy** [comment]
@ChildishhAlbino i just updated again...I actually needed to update the download url with all of these hoyo changes, go ahead and simply hit Install HoyoPlay like you regularly would and then make sure to press update. The update should actually update this time.

**Comment by ChildishhAlbino** [comment]
Ok it's a bit buggy (took me a few tries) but I got it working with the update now. Thanks for that @moraroy

**Comment by moraroy** [comment]
@ChildishhAlbino yeah it's a little buggy, closing genshin freezes the whole deck too.... you may have to do your fix of downloading and installing ge 9-4 and then going inside of the genshin launch options and replace the name of the umu proton with 9-4, you'd have to replace the whole name, make it look like the name of the force compatability option.

**Comment by ChildishhAlbino** [comment]
> you may have to do your fix of downloading and installing ge 9-4
I haven't actually tried this - I only forced the Hoyoplay launcher to use 9-4 over 9-27 using Steams built in compatibility options. This provided the most stable experience before your recent updates. I'll try doing this with the updated version.

**Comment by moraroy** [comment]
@ChildishhAlbino I actually just tested it, it still doesn't exit nicely haha I think the issue is genshin exiting with umu/ge

**Comment by ChildishhAlbino** [comment]
Happy to close this issue as it has been resolved - will continue discussions on #48

**Comment by bomairinge** [comment]
Not sure if it's worth opening but after updating (I'm using the newest version of NSL 4.1.4) I'm still having the issue of the game launcher/game (in this instance Zenless Zone Zero) not opening when I click play
